apiVersion: apps/v1 
kind: Deployment
metadata:
  name: kubernetes-demo-frontend-car
  labels: 
     app: car

spec:
  replicas: 1 
  selector:
    matchLabels:
      app: car

  template:
    metadata:
      labels:
        app: car
    spec:
      containers:
      - name: car
        image: DOCKER_IMAGE
        imagePullPolicy: Always
        ports:
        - containerPort: 80
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
