apiVersion: v1
kind: Service
metadata:
  name: frontend-car-svc
  labels:
    app: car
spec:
  selector:
    app: car

  ports:
    - port: 80
      targetPort: 80

  type: LoadBalancer
